version: "3"
services:
  bg-eraser:
    image: bg-eraser
    build:
      context: . 
      dockerfile: Dockerfile 
    volumes:
      - /root/utils/model/:/app/model/
    ports:
      - 8080:8080
    restart: always
